<x-layouts.app title="Ocorrências" active="occurrences">
    <header class="page-header"><div><h1>Ocorrências</h1><p>Fila operacional para abertura, análise e encaminhamento.</p></div>@can('create', \App\Models\Occurrence::class)<div class="page-header__actions"><x-ui.button :href="route('occurrences.create')" variant="primary"><x-ui.icon name="plus" /> Nova ocorrência</x-ui.button></div>@endcan</header>
    <form method="GET" class="filter-bar filter-bar--wrap">
        @if ($schools->count() > 1)<select name="school_id" aria-label="Escola"><option value="">Todas as escolas</option>@foreach ($schools as $school)<option value="{{ $school->id }}" @selected(request('school_id') == $school->id)>{{ $school->name }}</option>@endforeach</select>@endif
        <input type="search" name="search" value="{{ request('search') }}" placeholder="Protocolo ou título">
        <select name="status" aria-label="Situação"><option value="">Todas as situações</option>@foreach (\App\Models\Occurrence::STATUS_LABELS as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select>
        <select name="category_id" aria-label="Categoria"><option value="">Todas as categorias</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected(request('category_id') == $category->id)>{{ $category->name }}</option>@endforeach</select>
        <select name="environment_id" aria-label="Ambiente"><option value="">Todos os ambientes</option>@foreach ($environments as $environment)<option value="{{ $environment->id }}" @selected(request('environment_id') == $environment->id)>{{ $environment->name }}</option>@endforeach</select>
        <select name="impact" aria-label="Impacto"><option value="">Todos os impactos</option>@foreach (\App\Models\Occurrence::IMPACTS as $value => $label)<option value="{{ $value }}" @selected(request('impact') === $value)>{{ $label }}</option>@endforeach</select>
        <select name="priority" aria-label="Prioridade"><option value="">Todas as prioridades</option>@foreach (\App\Models\Occurrence::PRIORITIES as $value => $label)<option value="{{ $value }}" @selected(request('priority') === $value)>{{ $label }}</option>@endforeach</select>
        <input type="date" name="date_from" value="{{ request('date_from') }}" aria-label="Data inicial"><input type="date" name="date_to" value="{{ request('date_to') }}" aria-label="Data final"><x-ui.button type="submit">Filtrar</x-ui.button>
    </form>
    <section class="table-card"><table class="data-table"><thead><tr><th>Protocolo</th><th>Título</th><th>Ambiente</th><th>Categoria</th><th>Solicitante</th><th>Impacto</th><th>Prioridade</th><th>Tempo aberto</th><th>Data</th><th>Situação</th></tr></thead><tbody>
        @forelse ($occurrences as $occurrence)<tr class="clickable-row" onclick="window.location='{{ route('occurrences.show', $occurrence) }}'">
            <td><strong>{{ $occurrence->protocol }}</strong></td><td><strong>{{ $occurrence->title }}</strong><small>{{ $occurrence->school->name }}</small></td><td>{{ $occurrence->environment->name }}</td><td>{{ $occurrence->category->name }}</td><td>{{ $occurrence->reporter->name }}</td><td>{{ \App\Models\Occurrence::IMPACTS[$occurrence->impact] }}</td><td><span class="priority priority--{{ strtolower($occurrence->priority()) }}">{{ \App\Models\Occurrence::PRIORITIES[$occurrence->priority()] }}</span></td><td>{{ $occurrence->created_at->diffForHumans(short: true) }}</td><td>{{ $occurrence->created_at->format('d/m/Y H:i') }}</td><td><span class="badge badge--primary">{{ \App\Models\Occurrence::STATUS_LABELS[$occurrence->status] }}</span></td>
        </tr>@empty <tr><td colspan="10" class="empty-state">Nenhuma ocorrência encontrada.</td></tr>@endforelse
    </tbody></table></section>
</x-layouts.app>
